# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followedshows',
            name='show',
        ),
        migrations.AddField(
            model_name='followedshows',
            name='air_days',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followedshows',
            name='network',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followedshows',
            name='show_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followedshows',
            name='show_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followedshows',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
