# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170904_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='followedshows',
            name='air_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
