# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170914_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwatchedEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.IntegerField()),
                ('episode_name', models.TextField()),
                ('season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('air_time', models.TimeField()),
                ('air_date', models.DateField()),
                ('air_stamp', models.DateTimeField()),
                ('summary', models.TextField()),
                ('followed_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FollowedShows')),
            ],
            options={
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
