# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_unwatchedepisode_watched'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unwatchedepisode',
            unique_together=set([('followed_show', 'episode_id')]),
        ),
    ]
